### ISSUE TITLE
Extra DLLs Nor Recognised By Plugin

### ISSUE THREAD

**Issue by Philip-radioamateur** [JvanKatwijk/SDRunoPlugin_drm#1]
Hello Jvan,

Firstly to thank you for this great development!

I installed the three extra dlls in the Community Plugins folder (same place as the main DRM plugin) but the dll(s) are not found by the plugin.  Please have I put them in the correct folder?

The plugin locks onto DRM broadcasts OK but asks me to load the dll(s) so I only get three green lights even though the dlls are in the folder.

My setup is:
SDRuno V1.41
Windows 10 64bit
SDRPlay RSP1A

Philip.

Philip.

**Comment by JvanKatwijk** [comment]
The folder containing the community plugins is NOT (standard) in the search path that windows uses for finding dll's
I have - being a simple Linux programmer - no idea how to inspect or alter the search path, I do know however that the
folder for the SDRuno (C:\Program Files (x86)\SDRplay\SDRuno) is in the search path.
In my own environment I added the three dll's, equired for decoding the AAC segments, to that folder

**Comment by Philip-radioamateur** [comment]
Thank you.  I have placed the files in the C:\Program Files (x86)\SDRplay\SDRuno folder and it is now working.  Thanks again for an excellent plugin.
